OnlineOrganizationManagementSystem/Models/PublicHoliday.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineOrganizationManagementSystem.Models
{
    public class PublicHoliday
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public DateTime Date { get; set; }
    }
}

OnlineOrganizationManagementSystem/Controllers/PublicHolidaysController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineOrganizationManagementSystem.Data;
using OnlineOrganizationManagementSystem.Models;

namespace OnlineOrganizationManagementSystem.Controllers
{
    public class PublicHolidaysController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PublicHolidaysController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PublicHolidays
        [Authorize(Roles = "Admin, User, Manager")]
        public async Task<IActionResult> Index()
        {
            return _context.PublicHoliday != null ?
                        View(await _context.PublicHoliday.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.PublicHoliday'  is null.");
        }

        // GET: PublicHolidays/Details/5
        [Authorize(Roles = "Admin, User, Manager")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PublicHoliday == null)
            {
                return NotFound();
            }

            var publicHoliday = await _context.PublicHoliday
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publicHoliday == null)
            {
                return NotFound();
            }

            return View(publicHoliday);
        }

        // GET: PublicHolidays/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: PublicHolidays/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Date")] PublicHoliday publicHoliday)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publicHoliday);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publicHoliday);
        }

        // GET: PublicHolidays/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PublicHoliday == null)
            {
                return NotFound();
            }

            var publicHoliday = await _context.PublicHoliday.FindAsync(id);
            if (publicHoliday == null)
            {
                return NotFound();
            }
            return View(publicHoliday);
        }

        // POST: PublicHolidays/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Date")] PublicHoliday publicHoliday)
        {
            if (id != publicHoliday.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publicHoliday);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublicHolidayExists(publicHoliday.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publicHoliday);
        }

        // GET: PublicHolidays/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PublicHoliday == null)
            {
                return NotFound();
            }

            var publicHoliday = await _context.PublicHoliday
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publicHoliday == null)
            {
                return NotFound();
            }

            return View(publicHoliday);
        }

        // POST: PublicHolidays/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PublicHoliday == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PublicHoliday'  is null.");
            }
            var publicHoliday = await _context.PublicHoliday.FindAsync(id);
            if (publicHoliday != null)
            {
                _context.PublicHoliday.Remove(publicHoliday);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublicHolidayExists(int id)
        {
            return (_context.PublicHoliday?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OnlineOrganizationManagementSystem/Views/PublicHolidays/Create.cshtml
@model OnlineOrganizationManagementSystem.Models.PublicHoliday

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PublicHoliday</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineOrganizationManagementSystem/Views/PublicHolidays/Delete.cshtml
@model OnlineOrganizationManagementSystem.Models.PublicHoliday

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PublicHoliday</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OnlineOrganizationManagementSystem/Views/PublicHolidays/Details.cshtml
@model OnlineOrganizationManagementSystem.Models.PublicHoliday

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PublicHoliday</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

OnlineOrganizationManagementSystem/Views/PublicHolidays/Edit.cshtml
@model OnlineOrganizationManagementSystem.Models.PublicHoliday

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PublicHoliday</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineOrganizationManagementSystem/Views/PublicHolidays/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<OnlineOrganizationManagementSystem.Models.PublicHoliday>
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Index";
}
<div class="container">
    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <a asp-action="Create" class="btn btn-secondary mb-3">+ Create Holiday</a>
    }
    <div id='calendar'></div>
</div>

@section scripts {
    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var calendarEl = document.getElementById('calendar');

                var calendar = new FullCalendar.Calendar(calendarEl, {
                    initialView: 'dayGridMonth',
                    headerToolbar: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay'
                    },

                    selectable: true,
                    editable: false,
                    events: [
            @foreach (var item in Model)
            {
                var editUrl = Url.Action("Edit", "PublicHolidays", new { id = item.Id });
                var deleteUrl = Url.Action("Delete", "PublicHolidays", new { id = item.Id });
                @Html.Raw("{")
                @Html.Raw($"title: '{item.Title}',")
                @Html.Raw($"start: '{item.Date.ToString("yyyy-MM-dd")}',")
                @Html.Raw($"url: '{editUrl}',")
                @Html.Raw($"editUrl: '{editUrl}',")
                @Html.Raw($"deleteUrl: '{deleteUrl}',")
                @Html.Raw("},")
            }
                            ],
                    eventClick: function (info) {

                        // prevent navigating to the event URL
                        info.jsEvent.preventDefault();


                        // create the modal
                        var modal = document.createElement('div');
                        modal.classList.add('modal');

                        // add the modal content
                        modal.innerHTML = '<div class="modal-content">' +
                            '<h3>Actions for ' + info.event.title + '</h3>' +
                            '<div class="d-flex justify-content-center m-2">' +
                            '<a href="' + info.event.extendedProps.editUrl + '" class="btn btn-primary mx-2">Edit</a>' +
                            '<a href="' + info.event.extendedProps.deleteUrl + '" class="btn btn-danger mx-2">Delete</a>' +
                            '</div>' +
                            '</div>';

                        // add the modal to the page
                        document.body.appendChild(modal);

                        // close the modal when clicking outside of it
                        window.addEventListener('click', function (event) {
                            if (event.target == modal) {
                                modal.remove();
                            }
                        });

                    }

                });

                calendar.render();
            });
        </script>
    }
    else
    {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var calendarEl = document.getElementById('calendar');

                var calendar = new FullCalendar.Calendar(calendarEl, {
                    initialView: 'dayGridMonth',
                    headerToolbar: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay'
                    },

                    selectable: true,
                    editable: false,
                    events: [
            @foreach (var item in Model)
            {
                var editUrl = Url.Action("Edit", "PublicHolidays", new { id = item.Id });
                var deleteUrl = Url.Action("Delete", "PublicHolidays", new { id = item.Id });
                @Html.Raw("{")
                @Html.Raw($"title: '{item.Title}',")
                @Html.Raw($"start: '{item.Date.ToString("yyyy-MM-dd")}',")
  
                @Html.Raw("},")
            }
                                        ],
            
                 

                });

                calendar.render();
            });
        </script>
    }


    <style>
        .modal {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .modal-content {
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
            width: 30%;
            text-align: center;
        }

      

     
    </style>
}