OnlineOrganizationManagementSystem/Controllers/MailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineOrganizationManagementSystem.Data;
using OnlineOrganizationManagementSystem.Models;

namespace OnlineOrganizationManagementSystem.Controllers
{
    public class MailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public MailsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Mails
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            return _context.Mail != null ?
                          View(await _context.Mail.Where(n => (n.SenderMail == currentUser.UserName) || (n.ReceiverMail == currentUser.UserName)).OrderByDescending(d => d.DateCreated).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Mail'  is null.");
        }

        // GET: Mails/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Mail == null)
            {
                return NotFound();
            }

            var mail = await _context.Mail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mail == null)
            {
                return NotFound();
            }

            return View(mail);
        }

        [Authorize]
        // GET: Mails/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Create(string sender, string receiver, string subject, string body, int taskId)
        {
            var mail = new Messages
            {
                SenderMail = sender,
                ReceiverMail = receiver,
                Subject = subject,
                Body = body,
                Status = "Opened",
                DateCreated = DateTime.Now
            };
            var task = await _context.Tasks.FindAsync(taskId);
            if (task != null)
            {
                task.Status = "Review";
                _context.Tasks.Update(task);
                await _context.SaveChangesAsync();
            }
            return View(mail);
        }

        // POST: Mails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SenderMail,ReceiverMail,Subject,Body,DateCreated,Status")] Messages mail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mail);
        } 
 
        [Authorize(Roles ="Admin, Manager, User")]
        // GET: Mails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Mail == null)
            {
                return NotFound();
            }

            var mail = await _context.Mail.FindAsync(id);
            if (mail == null)
            {
                return NotFound();
            }
            return View(mail);
        }

        // POST: Mails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager, User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SenderMail,ReceiverMail,Subject,Body,DateCreated,Status")] Messages mail)
        {
            if (id != mail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MailExists(mail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mail);
        }

        // GET: Mails/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Mail == null)
            {
                return NotFound();
            }

            var mail = await _context.Mail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mail == null)
            {
                return NotFound();
            }

            return View(mail);
        }

        // POST: Mails/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Mail == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Mail'  is null.");
            }
            var mail = await _context.Mail.FindAsync(id);
            if (mail != null)
            {
                _context.Mail.Remove(mail);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MailExists(int id)
        {
          return (_context.Mail?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OnlineOrganizationManagementSystem/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineOrganizationManagementSystem.Data;
using OnlineOrganizationManagementSystem.Models;

namespace OnlineOrganizationManagementSystem.Controllers
{

    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public NotesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [Authorize]        
        // GET: Notes
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var notes = await _context.Notes
                .Where(n => n.UserId == user.Id)
                .ToListAsync();

            return View(notes);
        }

        [Authorize]        
        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notes == null)
            {
                return NotFound();
            }

            var notes = await _context.Notes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }


        [Authorize]
        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Content,Priority,UserId")] Notes notes)
        {
            var user = await _userManager.GetUserAsync(User);
            notes.UserId = user.Id;
            Console.WriteLine(notes.UserId);
            _context.Add(notes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            
        }
        // GET: Notes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notes == null)
            {
                return NotFound();
            }

            var notes = await _context.Notes.FindAsync(id);
            if (notes == null)
            {
                return NotFound();
            }
            return View(notes);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Priority,UserId")] Notes notes)
        {
            if (id != notes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(notes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotesExists(notes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(notes);
        }
        [Authorize]
        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notes == null)
            {
                return NotFound();
            }

            var notes = await _context.Notes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notes == null)
            {
                return NotFound();
            }

            return View(notes);
        }
        [Authorize]
        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notes'  is null.");
            }
            var notes = await _context.Notes.FindAsync(id);
            if (notes != null)
            {
                _context.Notes.Remove(notes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotesExists(int id)
        {
          return (_context.Notes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OnlineOrganizationManagementSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using OnlineOrganizationManagementSystem.Data
@inject ApplicationDbContext _context

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineOrganization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.6/index.global.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="~/OnlineOrganizationManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="glass">
            <ul>
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                            <img src="./Assets/teamsynclogo.svg" width="20" />
                        
                        <span class="special-text">
                            <a asp-area="Identity" asp-page="/Account/Manage/Index"> Hello @User.Identity.Name</a>
                        </span>
                    </li> 
                    <li class="nav-item">
                        <i class="bx bxs-calendar-alt"></i>
                        <span>
                            <a asp-area="" asp-controller="CalendarEvents"
                           asp-action="Index">Calendar</a>
                        </span>
                    </li>
                    <li class="nav-item">
                        <i class="bx bxs-bell"></i>
                        <span>
                            <a asp-area="" asp-controller="Mails"
                           asp-action="Index">Updates</a>
                        </span>
                    </li>


                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <i class="bx bxs-user"></i>
                            <span>
                                <a asp-area="" asp-controller="Usermanagement"
                           asp-action="Index">Users</a>
                            </span>
                        </li>
                        <li class="nav-item">
                            <i class="bx bx-bookmarks"></i>
                            <span>
                                <a asp-area="" asp-controller="CalendarEvents"
                           asp-action="EventTable">Events</a>
                            </span>
                        </li>
                    }
                    @if (!User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <i class="bx bxs-dashboard"></i>
                            <span><a asp-area="" asp-controller="Home" asp-action="Dashboard">Dashboard</a></span>
                        </li>
                        <li class="nav-item">
                            <i class="bx bxs-note"></i>
                            <span><a asp-area="" asp-controller="Notes" asp-action="Index">Notes</a></span>
                        </li>
                        <li class="nav-item">
                            <i class="bx bxs-hourglass"></i>
                            <span>
                                <a asp-area="" asp-controller="AttendanceRecords"
                           asp-action="Index">Workbook</a>
                            </span>
                        </li>
                       
                        <li class="nav-item">
                            <i class="bx bxs-group"></i>
                            <span><a asp-area="" asp-controller="Teams" asp-action="Index">Teams</a></span>
                        </li>
                        @if (_context.Teams.Any(t => t.UIUXDeveloperId == UserManager.GetUserId(User) ||
                       t.FrontendDeveloperId ==
                       UserManager.GetUserId(User) || t.BackendDeveloperId == UserManager.GetUserId(User) ||
                       t.TesterId ==
                       UserManager.GetUserId(User) || t.TeamLeadId == UserManager.GetUserId(User) ||
                       t.ReportsToId ==
                       UserManager.GetUserId(User)))
                        {
                            <li class="nav-item">
                                <i class="bx bx-task"></i>
                                <span><a asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a></span>
                            </li>
                            <li class="nav-item">
                                <i class="bx bx-coin"></i>
                                <span>
                                    <a asp-area="" asp-controller="Expenses"
                           asp-action="Index">Expenses</a>
                                </span>
                            </li>
                        }
                    }
                    @if (User.IsInRole("Manager"))
                    {
                        <li class="nav-item">
                            <i class="bx bxs-archive"></i>
                            <span>
                                <a asp-area="" asp-controller="Teams"
                           asp-action="Archival">Archives</a>
                            </span>
                        </li>
                        @*  @if (_context.Teams.Any(t => t.UIUXDeveloperId == UserManager.GetUserId(User) ||
                               t.FrontendDeveloperId ==
                               UserManager.GetUserId(User) || t.BackendDeveloperId == UserManager.GetUserId(User) ||
                               t.TesterId ==
                               UserManager.GetUserId(User) || t.TeamLeadId == UserManager.GetUserId(User) ||
                               t.ReportsToId ==
                               UserManager.GetUserId(User)))
                                {
                                   <li class="nav-item">
                        <i class="bx bx-video"></i>
                                        <span>
                                            <a asp-area="" asp-controller="Meetings"
                                   asp-action="Index">Meetings</a>
                                        </span>
                                    </li>

                        }*@
                       
                    }
                 
                }
                <partial name="_LoginPartial" />
            </ul>
        </nav>
    </header>
       
    <div class="container">
        <div class="fade-in">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    </div>

    @* <footer class="border-top footer text-muted">
       <div class="container">
            &copy; 2023 - AuthWithRolesTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>