OnlineOrganizationManagementSystem/Models/CalendarEvent.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineOrganizationManagementSystem.Models
{
    public class CalendarEvent
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public DateTime Date { get; set; }
    }
}

OnlineOrganizationManagementSystem/Controllers/CalendarEventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OnlineOrganizationManagementSystem.Data;
using OnlineOrganizationManagementSystem.Models;

namespace OnlineOrganizationManagementSystem.Controllers
{
    public class CalendarEvents : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CalendarEvents(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: CalendarEvents
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EventTable()
        {
            var holidays = await _context.CalendarEvent.ToListAsync();
            return View(holidays);
        }

        [Authorize(Roles = "Admin, User, Manager")]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var currentTeams = await _context.Teams
                .Where(t => t.UIUXDeveloperId == currentUser.Id || t.FrontendDeveloperId == currentUser.Id || t.BackendDeveloperId == currentUser.Id || t.TesterId == currentUser.Id || t.TeamLeadId == currentUser.Id || t.ReportsToId == currentUser.Id)
                .ToListAsync();

            List<CalendarEvent> calendarEvents = new List<CalendarEvent>();

            if (currentTeams == null || currentTeams.Count() < 1)
            {
                var events = await _context.CalendarEvent.ToListAsync();

                calendarEvents.AddRange(events.Select(e => new CalendarEvent
                {
                    Title = e.Title,
                    Date = e.Date,
                }));
            }
            else
            {

                foreach (var currentTeam in currentTeams)
                {
                    var meetings = await _context.Meetings.Where(m => m.TeamId == currentTeam.Id).ToListAsync();
                    var allEvents = await _context.CalendarEvent.ToListAsync();

                    calendarEvents.AddRange(meetings.Select(m => new CalendarEvent
                    {
                        Title = m.Title,
                        Date = m.Date,
                    }).Union(allEvents.Select(e => new CalendarEvent
                    {
                        Title = e.Title,
                        Date = e.Date,
                    })));
                }
                
            }

            var distinctEvents = calendarEvents
                .GroupBy(e => e.Title)
                .Select(g => g.First())
                .OrderBy(e => e.Date)
                .ToList();

            return View(distinctEvents);
        }

        // GET: CalendarEvents/Details/5
        [Authorize(Roles = "Admin, User, Manager")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CalendarEvent == null)
            {
                return NotFound();
            }

            var CalendarEvent = await _context.CalendarEvent
                .FirstOrDefaultAsync(m => m.Id == id);
            if (CalendarEvent == null)
            {
                return NotFound();
            }

            return View(CalendarEvent);
        }

        // GET: CalendarEvents/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: CalendarEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Date")] CalendarEvent CalendarEvent)
        {
            
                _context.Add(CalendarEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
         
        }

        // GET: CalendarEvents/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CalendarEvent == null)
            {
                return NotFound();
            }

            var CalendarEvent = await _context.CalendarEvent.FindAsync(id);
            if (CalendarEvent == null)
            {
                return NotFound();
            }
            return View(CalendarEvent);
        }

        // POST: CalendarEvents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Date")] CalendarEvent CalendarEvent)
        {
            if (id != CalendarEvent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(CalendarEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CalendarEventExists(CalendarEvent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(CalendarEvent);
        }

        // GET: CalendarEvents/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CalendarEvent == null)
            {
                return NotFound();
            }

            var CalendarEvent = await _context.CalendarEvent
                .FirstOrDefaultAsync(m => m.Id == id);
            if (CalendarEvent == null)
            {
                return NotFound();
            }

            return View(CalendarEvent);
        }

        // POST: CalendarEvents/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CalendarEvent == null)
            {
                return Problem("Entity set 'ApplicationDbContext.CalendarEvent'  is null.");
            }
            var CalendarEvent = await _context.CalendarEvent.FindAsync(id);
            if (CalendarEvent != null)
            {
                _context.CalendarEvent.Remove(CalendarEvent);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CalendarEventExists(int id)
        {
            return (_context.CalendarEvent?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OnlineOrganizationManagementSystem/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MimeKit;
using NuGet.Protocol.Plugins;
using OnlineOrganizationManagementSystem.Data;
using OnlineOrganizationManagementSystem.Models;
using Org.BouncyCastle.Utilities.IO;

namespace OnlineOrganizationManagementSystem.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public MeetingsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Meetings
        [Authorize(Roles = "User, Manager")]
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var currentTeams = await _context.Teams
                 .Where(t => t.UIUXDeveloperId == currentUser.Id || t.FrontendDeveloperId == currentUser.Id || t.BackendDeveloperId == currentUser.Id || t.TesterId == currentUser.Id || t.TeamLeadId == currentUser.Id || t.ReportsToId == currentUser.Id)
                 .ToListAsync();
            Console.WriteLine("Called Team Index");
            var events = new List<Meeting>();
            foreach (var currentTeam in currentTeams)
            {
                events.AddRange(await _context.Meetings.Where(m => m.TeamId == currentTeam.Id).ToListAsync());
            }
            return View(events);
          
        }

        // GET: Meetings/Details/5
        [Authorize(Roles = "User, Manager")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Meetings == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
              .Include(m => m.Team)
              .FirstOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // GET: Meetings/Create
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> CreateAsync()
        {
            ViewBag.MeetTeamId = "";
            var currentUser = await _userManager.GetUserAsync(User);
            ViewBag.MeetTeamId = new SelectList(_context.Teams.Where(n => n.ReportsToId == currentUser.Id), "Id", "Name");
            return View();
        }

        // POST: Meetings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventType,Title,Details,TeamId,Date")] Meeting meeting)
        {
            var team = await _context.Teams.FindAsync(meeting.TeamId);

            if (team == null)
            {
                return NotFound();
            }

            // Get the user emails
            var users = await _context.Users
                .Where(u => u.Id == team.UIUXDeveloperId
                         || u.Id == team.FrontendDeveloperId
                         || u.Id == team.BackendDeveloperId
                         || u.Id == team.TesterId
                         || u.Id == team.TeamLeadId
                         || u.Id == team.ReportsToId)
                .ToListAsync();
            _context.Add(meeting);
            await _context.SaveChangesAsync();
           

            foreach (var user in users)
            {
                await SendEmailAsync("krithikanithyanandam7@gmail.com", "Meeting Scheduled", $"Your meeting has been scheduled for {meeting.Title} on {meeting.Date} \nReceiver Mail: {user.Email}");
                
            }
            return RedirectToAction(nameof(Index));

        }


        // Mail server
        public async Task SendEmailAsync(string recipientEmail, string subject, string messageBody)
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("promote.n0replymailer@gmail.com", "promote.n0replymailer@gmail.com"));
            message.To.Add(new MailboxAddress("Admin", recipientEmail));
            message.Subject = subject;

            message.Body = new TextPart("plain")
            {
                Text = messageBody
            };

            using (var client = new SmtpClient())
            {
                await client.ConnectAsync("smtp.gmail.com", 587, false);
                await client.AuthenticateAsync("promote.n0replymailer@gmail.com", "ashqtcouelkfiznr");
                await client.SendAsync(message);
                await client.DisconnectAsync(true);
            }
        }

        // GET: Meetings/Edit/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Meetings == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings.FindAsync(id);
            if (meeting == null)
            {
                return NotFound();
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "Name", meeting.TeamId);
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventType,Title,Details,TeamId,Date")] Meeting meeting)
        {
            if (id != meeting.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Update(meeting);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MeetingExists(meeting.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

            //ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "Name", meeting.TeamId);
            //return View(meeting);
        }

        // GET: Meetings/Delete/5
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Meetings == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
              .Include(m => m.Team)
              .FirstOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // POST: Meetings/Delete/5
        [Authorize(Roles = "Manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Meetings == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Meetings'  is null.");
            }
            var meeting = await _context.Meetings.FindAsync(id);
            if (meeting != null)
            {
                _context.Meetings.Remove(meeting);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingExists(int id)
        {
            return (_context.Meetings?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OnlineOrganizationManagementSystem/Views/CalendarEvents/Create.cshtml
@model OnlineOrganizationManagementSystem.Models.CalendarEvent

@{
    ViewData["Title"] = "Create";
}


<div class="row justify-content-center">
    <div class="col-md-7 p-5 card mt-2 border-0 shadow">
        <h2 class="my-3 fw-bolder">Create Event</h2>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group my-2">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" type="date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div> 
           
            <div class="form-group my-2">
                <input type="submit" value="Create" class="w-100 btn btn-lg mt-2 btn-primary" />
                <a asp-action="Index" class="w-100 btn btn-lg mt-2 btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineOrganizationManagementSystem/Views/CalendarEvents/Delete.cshtml
@model OnlineOrganizationManagementSystem.Models.CalendarEvent

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CalendarEvent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OnlineOrganizationManagementSystem/Views/CalendarEvents/Details.cshtml
@model OnlineOrganizationManagementSystem.Models.CalendarEvent

@{
    ViewData["Title"] = "Details";
}

<div class="mx-5 d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="bg-primary-glass p-3">
        <h2 class="fw-bolder mt-2">@ViewData["Title"]</h2>
        <hr />
        <dl class="row ">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        </dl>
        <div>
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
            <a asp-action="Index" class="btn btn-primary">Back to List</a>
        </div>
    </div>
</div>

OnlineOrganizationManagementSystem/Views/CalendarEvents/Edit.cshtml
@model OnlineOrganizationManagementSystem.Models.CalendarEvent

@{
    ViewData["Title"] = "Edit";
}

<div class="row justify-content-center">
    <div class="col-md-7 p-5 card mt-2 border-0 shadow">
        <h2 class="my-3 fw-bolder">@ViewData["Title"]</h2>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group my-2">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div> 
            
            <div class="form-group my-2">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group my-2">
                <input type="submit" value="Save" class="w-100 btn btn-lg mt-2 btn-primary" />
                <a asp-action="Index" class="w-100 btn btn-lg mt-2 btn-primary">Back to List</a>

            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineOrganizationManagementSystem/Views/CalendarEvents/EventTable.cshtml
@model IEnumerable<OnlineOrganizationManagementSystem.Models.CalendarEvent>


<div class="d-flex justify-content-between align-items-center">
    <h2 class="fw-bolder my-4">
        Events
    </h2>
    <a asp-action="Create" class="btn btn-primary mt-4">+ Create New</a>

</div>

@if (!Model.Any())
{
    <div class=" bg-primary-glass p-4">
        <h4 class="text-center ">No Events yet!</h4>
    </div>

}
<div class="row my-6">
    @foreach (var item in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card bg-primary-glass">
                <div class="card-header">
                    <h5 class="card-title mt-2">@Html.DisplayFor(modelItem => item.Title)</h5>
                
                    @Html.DisplayFor(modelItem => item.Date)
                </div>
                <div class="card-footer">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary float-right"><i class="fas fa-pencil-alt"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger float-right mr-2"><i class="fas fa-trash-alt"></i></a>
                </div>
            </div>
        </div>
    }
</div>

OnlineOrganizationManagementSystem/Views/CalendarEvents/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<OnlineOrganizationManagementSystem.Models.CalendarEvent>
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using OnlineOrganizationManagementSystem.Data
@inject ApplicationDbContext _context
@{
    ViewData["Title"] = "Index";
}

   
    <div class="glass container p-5 shadow border-0">
        @if ((SignInManager.IsSignedIn(User) && User.IsInRole("Admin")))
        {

            <a asp-action="EventTable" class="btn btn-secondary mb-3">Event Controls</a>

        }
        @if ((SignInManager.IsSignedIn(User) && User.IsInRole("Manager")))
        {
            @if (_context.Teams
           .Any(t => t.UIUXDeveloperId == UserManager.GetUserId(User) || t.FrontendDeveloperId == UserManager.GetUserId(User) || t.BackendDeveloperId == UserManager.GetUserId(User) || t.TesterId == UserManager.GetUserId(User) || t.TeamLeadId == UserManager.GetUserId(User) || t.ReportsToId == UserManager.GetUserId(User)))
            {
                <a asp-controller="Meetings" asp-action="Create" class="btn btn-secondary glass mb-3">+ Create Meeting</a>
                <a asp-controller="Meetings" asp-action="Index" class="btn btn-secondary glass mb-3">View Meetings</a>
            }

        }
        <div id='calendar'></div>
    </div>

@section scripts {
    
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var calendarEl = document.getElementById('calendar');
                var calendar = new FullCalendar.Calendar(calendarEl, {
                    initialView: 'dayGridMonth',
                    headerToolbar: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay'
                    },
                    selectable: true,
                    editable: false,
                    events: [
                @foreach (var item in Model)
                {
                    //var editUrl = Url.Action("Edit", "CalendarEvents", new { id = item.Id });
                    //var deleteUrl = Url.Action("Delete", "CalendarEvents", new { id = item.Id });
                    @Html.Raw("{")
                    @Html.Raw($"title: '{item.Title}',")
                    @Html.Raw($"start: '{item.Date.ToString("yyyy-MM-dd")}',")
                    //@Html.Raw($"url: '{editUrl}',")
                    //@Html.Raw($"editUrl: '{editUrl}',")
                    //@Html.Raw($"deleteUrl: '{deleteUrl}',")
                    @Html.Raw("},")
                }],
                    
                });
                calendar.render();
            });
        </script>
}